import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

const ONLINE_DOT = '#22c55e';

export function createSupportChatStyles(c: ThemeColors) {
  return StyleSheet.create({
    flex1: { flex: 1 },
    headerTitleCenter: {
      flex: 1,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
    },
    headerOnlineRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      marginTop: 2,
      gap: 6,
    },
    headerOnlineText: {
      fontSize: 12,
      fontWeight: '500' as const,
      letterSpacing: 0.2,
      color: c.success,
    },
    headerOnlineDot: {
      width: 7,
      height: 7,
      borderRadius: 3.5,
      backgroundColor: ONLINE_DOT,
    },
    messagesContent: {
      paddingHorizontal: 10,
      paddingTop: 12,
      paddingBottom: 8,
      flexGrow: 1,
    },
    emptyWrap: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 48,
      paddingHorizontal: 24,
    },
    emptyText: {
      fontSize: 15,
      color: c.textMuted,
      textAlign: 'center',
    },
    row: {
      width: '100%' as const,
      flexDirection: 'row',
      marginBottom: 8,
    },
    rowUser: {
      justifyContent: 'flex-end' as const,
    },
    rowSupport: {
      justifyContent: 'flex-start' as const,
    },
    bubbleUser: {
      maxWidth: '75%' as const,
      minWidth: 0,
      backgroundColor: c.accent,
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 8,
      overflow: 'hidden' as const,
    },
    bubbleUserImagePadding: {
      paddingHorizontal: 4,
      paddingVertical: 4,
    },
    bubbleSupport: {
      maxWidth: '75%' as const,
      minWidth: 0,
      backgroundColor: c.bgMuted,
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      overflow: 'hidden' as const,
    },
    bubbleSupportImagePadding: {
      paddingHorizontal: 4,
      paddingVertical: 4,
    },
    bubbleTextUser: {
      fontSize: 15,
      lineHeight: 21,
      color: c.onAccent,
    },
    bubbleTextSupport: {
      fontSize: 15,
      lineHeight: 21,
      color: c.text,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-end' as const,
      justifyContent: 'flex-end' as const,
      gap: 4,
      marginTop: 5,
    },
    timeInBubble: {
      fontSize: 11,
      color: 'rgba(255,255,255,0.85)',
    },
    timeInBubbleSupport: {
      fontSize: 11,
      color: c.textMuted,
      marginTop: 5,
      alignSelf: 'flex-start' as const,
    },
    ticksWrap: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    actionSheetContainer: {
      flex: 1,
      width: '100%' as const,
    },
    actionSheetLayerFill: {
      ...StyleSheet.absoluteFillObject,
    },
    actionSheetBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.4)',
      zIndex: 0,
    },
    actionSheetDismiss: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 1,
    },
    actionSheetCardWrap: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      paddingHorizontal: 20,
      zIndex: 2,
    },
    actionSheetCard: {
      width: '80%' as const,
      maxWidth: 340,
      backgroundColor: c.surface,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 16,
      elevation: 8,
    },
    actionSheetTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: c.textMuted,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 8,
    },
    actionSheetRow: {
      paddingVertical: 15,
      paddingHorizontal: 16,
    },
    actionSheetRowText: {
      fontSize: 16,
      color: c.text,
      fontWeight: '400',
    },
    actionSheetRowDanger: {
      color: c.danger,
      fontWeight: '500',
    },
    actionSheetSeparator: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: c.border,
      marginLeft: 16,
    },
    actionSheetCancelBlock: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      marginTop: 4,
      paddingTop: 2,
    },
    actionSheetCancelRow: {
      paddingVertical: 15,
      paddingHorizontal: 16,
    },
    actionSheetCancelText: {
      fontSize: 16,
      color: c.textMuted,
      fontWeight: '500',
      textAlign: 'center' as const,
    },
    typingFooter: {
      paddingVertical: 10,
      paddingHorizontal: 4,
    },
    typingText: {
      fontSize: 13,
      color: c.textMuted,
      fontStyle: 'italic',
    },
    sendingHint: {
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
      paddingHorizontal: 16,
      paddingBottom: 6,
    },
    composer: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      paddingHorizontal: 12,
      paddingTop: 10,
      gap: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      backgroundColor: c.bg,
    },
    attachBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 0,
      backgroundColor: c.inputBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.inputBorder,
    },
    attachBtnDisabled: {
      opacity: 0.5,
    },
    input: {
      flex: 1,
      minHeight: 44,
      maxHeight: 120,
      backgroundColor: c.inputBg,
      borderRadius: 20,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.inputBorder,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 15,
      color: c.text,
    },
    sendBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 0,
    },
    sendBtnDisabled: {
      opacity: 0.5,
    },
    centerFill: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    errorText: {
      color: c.danger,
      fontSize: 14,
      textAlign: 'center',
      marginTop: 12,
    },
    replyPreviewRow: {
      flexDirection: 'row',
      alignItems: 'center' as const,
      marginHorizontal: 12,
      marginTop: 6,
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: c.bgMuted,
      borderLeftWidth: 3,
      borderLeftColor: c.accent,
      borderRadius: 8,
    },
    replyPreviewContent: {
      flex: 1,
      minWidth: 0,
    },
    replyPreviewLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: c.accent,
      textTransform: 'uppercase' as const,
      letterSpacing: 0.4,
      marginBottom: 4,
    },
    replyPreviewText: {
      flex: 1,
      fontSize: 14,
      color: c.text,
    },
    replyPreviewTextRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    replyPreviewIcon: {
      marginRight: 2,
    },
    replyPreviewMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    replyPreviewCancel: {
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    replyPreviewCancelText: {
      fontSize: 14,
      color: c.accent,
    },
    replyQuoteInBubble: {
      paddingVertical: 6,
      paddingHorizontal: 8,
      marginBottom: 6,
      borderRadius: 6,
    },
    replyQuoteInBubbleUser: {
      backgroundColor: 'rgba(0,0,0,0.2)',
    },
    replyQuoteInBubbleSupport: {
      backgroundColor: c.inputBg,
    },
    replyQuoteInBubbleText: {
      fontSize: 12,
    },
    replyQuoteInBubbleTextUser: {
      color: 'rgba(255,255,255,0.9)',
    },
    replyQuoteInBubbleTextSupport: {
      color: c.textMuted,
    },
    imageViewerClose: {
      position: 'absolute',
      top: 0,
      right: 0,
      zIndex: 10,
      padding: 12,
    },
    /** Modal de permissão da galeria (antes do pedido do sistema) */
    galleryPermBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.45)',
    },
    galleryPermCard: {
      marginHorizontal: 24,
      maxWidth: 400,
      width: '100%' as const,
      alignSelf: 'center' as const,
      backgroundColor: c.surface,
      borderRadius: 16,
      paddingHorizontal: 20,
      paddingTop: 22,
      paddingBottom: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    galleryPermTitle: {
      fontSize: 18,
      fontWeight: '700' as const,
      color: c.text,
      marginBottom: 10,
    },
    galleryPermMessage: {
      fontSize: 15,
      lineHeight: 22,
      color: c.textSecondary,
      marginBottom: 20,
    },
    galleryPermRow: {
      flexDirection: 'row' as const,
      justifyContent: 'flex-end' as const,
      gap: 8,
    },
    galleryPermBtnGhost: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 12,
    },
    galleryPermBtnGhostText: {
      fontSize: 16,
      fontWeight: '600' as const,
      color: c.textSecondary,
    },
    galleryPermBtnPrimary: {
      paddingVertical: 12,
      paddingHorizontal: 18,
      borderRadius: 12,
      backgroundColor: c.accent,
    },
    galleryPermBtnPrimaryText: {
      fontSize: 16,
      fontWeight: '600' as const,
      color: c.onAccent,
    },
  });
}
