import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

/** Estilos partilhados — alinhados ao ecrã de Configurações (cards, tipografia) do motorista. */
export function createSettingsStyles(c: ThemeColors) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: c.bg },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
      backgroundColor: c.bg,
    },
    backBtn: { padding: 8 },
    topTitle: { fontSize: 17, fontWeight: '600', color: c.text },
    scroll: { paddingHorizontal: 16, paddingTop: 16 },
    sectionLabel: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.6,
      color: c.textMuted,
      textTransform: 'uppercase',
      marginBottom: 10,
      marginTop: 8,
      paddingHorizontal: 4,
    },
    menuCard: {
      backgroundColor: c.surface,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      marginBottom: 14,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 18,
      paddingHorizontal: 16,
    },
    rowBorder: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    menuLeft: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1, minWidth: 0 },
    menuIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    menuTextCol: { flex: 1, minWidth: 0 },
    menuTitle: { fontSize: 16, fontWeight: '600', color: c.text },
    menuSub: { marginTop: 3, fontSize: 13, color: c.textMuted, fontWeight: '400' },
    hint: {
      fontSize: 13,
      color: c.textMuted,
      lineHeight: 19,
      marginBottom: 16,
      paddingHorizontal: 4,
    },
    valueText: { fontSize: 13, color: c.textMuted, maxWidth: 140, textAlign: 'right' },
    switchRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 16,
      gap: 12,
    },
    primaryBtn: {
      marginHorizontal: 16,
      marginVertical: 12,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: c.accentMuted,
      alignItems: 'center',
    },
    primaryBtnText: { fontSize: 15, fontWeight: '700', color: c.accent },
    dangerBtn: {
      marginHorizontal: 16,
      marginVertical: 12,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: c.dangerMuted,
      alignItems: 'center',
    },
    dangerBtnText: { fontSize: 15, fontWeight: '700', color: c.danger },
    statusPill: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: c.chipBg,
    },
    statusPillOk: { backgroundColor: c.successBg },
    statusPillWarn: { backgroundColor: c.warningBg },
    statusPillText: { fontSize: 12, fontWeight: '700', color: c.text },
    monoSmall: { fontSize: 11, fontFamily: 'monospace', color: c.textMuted },
    list: { gap: 12 },
    option: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderRadius: 16,
      borderWidth: 1.5,
    },
    optionTextCol: { flex: 1, minWidth: 0, paddingRight: 12 },
    optionTitle: { fontSize: 16, fontWeight: '600', color: c.text },
    optionDesc: { marginTop: 4, fontSize: 12, color: c.textMuted, lineHeight: 17 },
    radio: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: c.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioInner: {
      width: 12,
      height: 12,
      borderRadius: 6,
    },
  });
}
